/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;

import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Car;
import model.FleetOfCars;

/**
 *
 * @author LENOVO
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    FleetOfCars allCars;
    public CreateJPanel(FleetOfCars allCars) {
        initComponents();
        this.allCars = allCars ; 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ttlAddCar = new javax.swing.JLabel();
        lblNameOfCar = new javax.swing.JLabel();
        lblYearOfManufacture = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtNameOfCar = new javax.swing.JTextField();
        txtModelName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtYearOfManufacture = new javax.swing.JTextField();
        txtNumberOfSeats = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        rdoMaintenanceCertificateNo = new javax.swing.JRadioButton();
        rdoMaintenanceCertificateYes = new javax.swing.JRadioButton();
        rdoAvailabilityNo = new javax.swing.JRadioButton();
        rdoAvailabilityYes = new javax.swing.JRadioButton();
        lblAvailability = new javax.swing.JLabel();
        lblNoOfSeats = new javax.swing.JLabel();
        btnAddCsv = new javax.swing.JButton();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();

        ttlAddCar.setBackground(new java.awt.Color(102, 102, 255));
        ttlAddCar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttlAddCar.setForeground(new java.awt.Color(51, 51, 255));
        ttlAddCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttlAddCar.setText("Add Car");

        lblNameOfCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNameOfCar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNameOfCar.setText("Name of Car");

        lblYearOfManufacture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYearOfManufacture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfManufacture.setText("Year Of Manufacture");

        lblModelNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Name");

        lblSerialNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLocation.setText("Location");

        txtNameOfCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameOfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameOfCarActionPerformed(evt);
            }
        });

        txtModelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtYearOfManufacture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNumberOfSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(255, 153, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 51, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMaintenanceCertificateNo);
        rdoMaintenanceCertificateNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoMaintenanceCertificateNo.setText("No");
        rdoMaintenanceCertificateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaintenanceCertificateNoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoMaintenanceCertificateYes);
        rdoMaintenanceCertificateYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoMaintenanceCertificateYes.setText("Yes");
        rdoMaintenanceCertificateYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaintenanceCertificateYesActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoAvailabilityNo);
        rdoAvailabilityNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoAvailabilityNo.setText("No");
        rdoAvailabilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAvailabilityNoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoAvailabilityYes);
        rdoAvailabilityYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoAvailabilityYes.setText("Yes");
        rdoAvailabilityYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAvailabilityYesActionPerformed(evt);
            }
        });

        lblAvailability.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAvailability.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailability.setText("Availability");

        lblNoOfSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoOfSeats.setText("No Of Seats");

        btnAddCsv.setBackground(new java.awt.Color(255, 153, 153));
        btnAddCsv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddCsv.setForeground(new java.awt.Color(51, 51, 255));
        btnAddCsv.setText("Add CSV");
        btnAddCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCsvActionPerformed(evt);
            }
        });

        lblMaintenanceCertificate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintenanceCertificate.setText("Maintenance certificate");

        txtSerialNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ttlAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaintenanceCertificate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNameOfCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYearOfManufacture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNoOfSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAvailability, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameOfCar, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(txtModelName)
                                    .addComponent(txtYearOfManufacture)
                                    .addComponent(txtNumberOfSeats)
                                    .addComponent(txtSerialNumber))
                                .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdoAvailabilityYes)
                                    .addComponent(rdoMaintenanceCertificateYes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoMaintenanceCertificateNo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoAvailabilityNo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddCsv)
                                .addGap(80, 80, 80)))))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblModelNumber, lblNameOfCar, lblSerialNumber, lblYearOfManufacture});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ttlAddCar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNameOfCar))
                        .addGap(18, 18, 18)
                        .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearOfManufacture)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblModelNumber)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoOfSeats))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocation))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMaintenanceCertificateYes)
                    .addComponent(rdoMaintenanceCertificateNo)
                    .addComponent(lblMaintenanceCertificate))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(rdoAvailabilityYes)
                    .addComponent(rdoAvailabilityNo))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnAddCsv))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameOfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameOfCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameOfCarActionPerformed

    private void rdoMaintenanceCertificateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaintenanceCertificateNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaintenanceCertificateNoActionPerformed

    private void rdoMaintenanceCertificateYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaintenanceCertificateYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaintenanceCertificateYesActionPerformed

    private void rdoAvailabilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAvailabilityNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAvailabilityNoActionPerformed

    private void rdoAvailabilityYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAvailabilityYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAvailabilityYesActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      
          if(
                  (txtModelName.getText().isEmpty())||
                  (txtModelName.getText().isEmpty())||
                  (txtYearOfManufacture.getText().isEmpty())||
                  (txtLocation.getText().isEmpty())||
                  (txtNumberOfSeats.getText().isEmpty())||
                  (buttonGroup1).getSelection()==null ||
                  (buttonGroup2).getSelection()==null
             ){
                JOptionPane.showMessageDialog(this, "Please fill all the fields!!!");
                return;
              
                }
          
         
        String nameOfCar = txtNameOfCar.getText();
        String  modelName = txtModelName.getText();
        int year = Integer.parseInt(txtYearOfManufacture.getText());
        int seats = Integer.parseInt(txtNumberOfSeats.getText());
        String  serialNumber = txtLocation.getText();
        String location = txtLocation.getText();
      
      
        Car car = allCars.addNewCar();
        
        car.setNameOfCar(nameOfCar);
        car.setModelName(modelName);
        car.setYearOfManufacture(year);
        car.setNoOfSeats(seats);
        car.setSerialNumber(serialNumber);
        car.setLocation(location);
        if(rdoAvailabilityYes.isSelected()){
            car.setAvailability("Yes");
            
        }
        else if(rdoAvailabilityNo.isSelected())
        {
            car.setAvailability("No");
          
        }
        
         if(rdoMaintenanceCertificateYes.isSelected()==true){
            car.setMaintenaceCertificate("Yes");
           
        }
        else if(rdoMaintenanceCertificateNo.isSelected()==true)
        {
            car.setMaintenaceCertificate("No");
        
        }
        
        
        JOptionPane.showMessageDialog(this, "new car saved");
        
        txtNameOfCar.setText("");
        txtModelName.setText("");
        txtYearOfManufacture.setText("");
        txtNumberOfSeats.setText("");
        txtLocation.setText("");
        txtSerialNumber.setText("");
        rdoMaintenanceCertificateNo.setSelected(false);
        rdoMaintenanceCertificateYes.setSelected(false);
        rdoAvailabilityNo.setSelected(false);
        rdoAvailabilityYes.setSelected(false);
      
        
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCsvActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\LENOVO\\Desktop\\carsData.csv";
        String line = "";
       
        {
            BufferedReader br;
            try
            {
                br = new BufferedReader(new FileReader(path));

            int i = 0;
            while((line=br.readLine()) != null){
                String[] values = line.split(",");
                Car car = allCars.addNewCar();
                car.setNameOfCar(values[0]);
                car.setModelName(values[1]);
                car.setYearOfManufacture(Integer.parseInt(values[2]));
                car.setNoOfSeats(Integer.parseInt(values[3]));
                car.setSerialNumber(values[4]);
                i++;
            }
            JOptionPane.showMessageDialog(this, String.valueOf(i) + " Cars are added into View Section");
                        } catch (FileNotFoundException ex)
            {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex)
            {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 
        
    }//GEN-LAST:event_btnAddCsvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCsv;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNameOfCar;
    private javax.swing.JLabel lblNoOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblYearOfManufacture;
    private javax.swing.JRadioButton rdoAvailabilityNo;
    private javax.swing.JRadioButton rdoAvailabilityYes;
    private javax.swing.JRadioButton rdoMaintenanceCertificateNo;
    private javax.swing.JRadioButton rdoMaintenanceCertificateYes;
    private javax.swing.JLabel ttlAddCar;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtNameOfCar;
    private javax.swing.JTextField txtNumberOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYearOfManufacture;
    // End of variables declaration//GEN-END:variables
}
