/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.FleetOfCars;

/**
 *
 * @author Kishore<your.name at your.org>
 */
public class SimpleSearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SimpleSearchJPanel
     */
   
    
    FleetOfCars allCars;
    public SimpleSearchJPanel(FleetOfCars allCars) {
        initComponents();
        this.allCars = allCars;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtFleetLastUpdated = new javax.swing.JTextField();
        txtFirstAvailableCar = new javax.swing.JTextField();
        txtTotalAvailableCars1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtTotalAvailableCars2 = new javax.swing.JTextField();
        btnFleetLastUpdated1 = new javax.swing.JButton();
        txtFleetLastUpdated1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txtTotalAvailableCars3 = new javax.swing.JTextField();
        txtTotalAvailableCars = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Total Available Cars");

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("First Available Car");

        jButton4.setText("Serial Number");

        txtFleetLastUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFleetLastUpdatedActionPerformed(evt);
            }
        });

        txtFirstAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstAvailableCarActionPerformed(evt);
            }
        });

        txtTotalAvailableCars1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAvailableCars1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Maximum Seats");

        txtTotalAvailableCars2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAvailableCars2ActionPerformed(evt);
            }
        });

        btnFleetLastUpdated1.setBackground(new java.awt.Color(204, 204, 255));
        btnFleetLastUpdated1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFleetLastUpdated1.setText("Fleet Last Updated");
        btnFleetLastUpdated1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetLastUpdated1ActionPerformed(evt);
            }
        });

        txtFleetLastUpdated1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFleetLastUpdated1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Total Unavailable Cars");

        txtTotalAvailableCars3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAvailableCars3ActionPerformed(evt);
            }
        });

        txtTotalAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAvailableCarsActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("Minimum Seats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFleetLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(btnFleetLastUpdated1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFleetLastUpdated1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(txtTotalAvailableCars3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotalAvailableCars2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtTotalAvailableCars1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstAvailableCar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(txtFirstAvailableCar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txtTotalAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAvailableCars3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFleetLastUpdated1)
                            .addComponent(txtFleetLastUpdated1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtFleetLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton4)))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(txtTotalAvailableCars1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtTotalAvailableCars2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(334, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFleetLastUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFleetLastUpdatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFleetLastUpdatedActionPerformed

    private void txtFirstAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstAvailableCarActionPerformed
        // TODO add your handling code here:
        txtFirstAvailableCar.setText(allCars.firstCar().getNameOfCar())   ;    
    }//GEN-LAST:event_txtFirstAvailableCarActionPerformed

    private void txtTotalAvailableCars1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAvailableCars1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAvailableCars1ActionPerformed

    private void txtTotalAvailableCars2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAvailableCars2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAvailableCars2ActionPerformed

    private void btnFleetLastUpdated1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetLastUpdated1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFleetLastUpdated1ActionPerformed

    private void txtFleetLastUpdated1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFleetLastUpdated1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFleetLastUpdated1ActionPerformed

    private void txtTotalAvailableCars3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAvailableCars3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAvailableCars3ActionPerformed

    private void txtTotalAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAvailableCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAvailableCarsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFleetLastUpdated1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField txtFirstAvailableCar;
    private javax.swing.JTextField txtFleetLastUpdated;
    private javax.swing.JTextField txtFleetLastUpdated1;
    private javax.swing.JTextField txtTotalAvailableCars;
    private javax.swing.JTextField txtTotalAvailableCars1;
    private javax.swing.JTextField txtTotalAvailableCars2;
    private javax.swing.JTextField txtTotalAvailableCars3;
    // End of variables declaration//GEN-END:variables
}
