/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.FleetOfCars;

/**
 *
 * @author Kishore<your.name at your.org>
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    FleetOfCars allCars;
    public ViewJPanel(FleetOfCars allCars) {
        initComponents();
        this.allCars = allCars;
        
         populateTable();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllCars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblAvailability = new javax.swing.JLabel();
        lblNameOfCar = new javax.swing.JLabel();
        lblYearOfManufacture = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblNoOfSeats = new javax.swing.JLabel();
        txtYearOfManufacture = new javax.swing.JTextField();
        lblSerialNumber = new javax.swing.JLabel();
        txtNoOfSeats = new javax.swing.JTextField();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtNameOfCar = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtModelName = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        ttlAddCar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 800));

        btnView.setBackground(new java.awt.Color(255, 153, 153));
        btnView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(51, 51, 255));
        btnView.setText("View");
        btnView.setPreferredSize(new java.awt.Dimension(80, 25));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 51, 255));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(80, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 255));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 25));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblAllCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name of Car", "Model Name", "Year of Man.", "No. of Seats", "Serial Number", "Location", "Maintenance Certificate", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllCars);

        lblAvailability.setBackground(new java.awt.Color(153, 204, 255));
        lblAvailability.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAvailability.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvailability.setText("Availability");

        lblNameOfCar.setBackground(new java.awt.Color(153, 204, 255));
        lblNameOfCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNameOfCar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNameOfCar.setText("Name of Car(Brand)");

        lblYearOfManufacture.setBackground(new java.awt.Color(153, 204, 255));
        lblYearOfManufacture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYearOfManufacture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfManufacture.setText("Year Of Manufacture");

        lblModelNumber.setBackground(new java.awt.Color(153, 204, 255));
        lblModelNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model Name");

        txtSerialNumber.setBackground(new java.awt.Color(153, 204, 255));
        txtSerialNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNoOfSeats.setBackground(new java.awt.Color(153, 204, 255));
        lblNoOfSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoOfSeats.setText("No Of Seats");

        txtYearOfManufacture.setBackground(new java.awt.Color(153, 204, 255));
        txtYearOfManufacture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSerialNumber.setBackground(new java.awt.Color(153, 204, 255));
        lblSerialNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial Number");

        txtNoOfSeats.setBackground(new java.awt.Color(153, 204, 255));
        txtNoOfSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMaintenanceCertificate.setBackground(new java.awt.Color(153, 204, 255));
        lblMaintenanceCertificate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintenanceCertificate.setText("Maintenance certificate");

        jRadioButton1.setBackground(new java.awt.Color(153, 204, 255));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setText("No");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        txtNameOfCar.setBackground(new java.awt.Color(153, 204, 255));
        txtNameOfCar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameOfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameOfCarActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(153, 204, 255));
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton2.setText("Yes");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        txtModelName.setBackground(new java.awt.Color(153, 204, 255));
        txtModelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jRadioButton3.setBackground(new java.awt.Color(153, 204, 255));
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton3.setText("No");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(153, 204, 255));
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton4.setText("Yes");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaintenanceCertificate)
                            .addComponent(lblAvailability))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNameOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNameOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameOfCar)
                    .addComponent(txtNameOfCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYearOfManufacture)
                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoOfSeats)
                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(lblAvailability))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ttlAddCar.setBackground(new java.awt.Color(102, 102, 255));
        ttlAddCar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttlAddCar.setForeground(new java.awt.Color(51, 51, 255));
        ttlAddCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttlAddCar.setText("View Details of Cars");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttlAddCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ttlAddCar)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAllCars.getSelectedRow();
           
           if (selectedRowIndex < 0){
               JOptionPane.showMessageDialog(this,"Select a row to display the data");
           }
           
           DefaultTableModel model = (DefaultTableModel) tblAllCars.getModel();
           Car car = (Car) model.getValueAt(selectedRowIndex, 0);
           
           txtNameOfCar.setText(car.getNameOfCar());
           txtModelName.setText(car.getModelName());
           txtYearOfManufacture.setText(String.valueOf(car.getYearOfManufacture()));
           txtNoOfSeats.setText(String.valueOf(car.getNoOfSeats()));
           txtSerialNumber.setText(car.getSerialNumber());
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblAllCars.getSelectedRow();
           
           if (selectedRowIndex < 0){
               JOptionPane.showMessageDialog(this,"Select a row to delete");
               return;
           }
           
           DefaultTableModel model = (DefaultTableModel) tblAllCars.getModel();
           Car car = (Car) model.getValueAt(selectedRowIndex, 0);
           
           allCars.deleteCar(car);
           JOptionPane.showMessageDialog(this,"Selected car removed from the fleet");
           populateTable();
           
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         int rowindex =  tblAllCars.getSelectedRow();
       if(rowindex<0){
           JOptionPane.showMessageDialog(this,"Please select a row to UPDATE");
           return;
       }
       
        DefaultTableModel model=(DefaultTableModel)tblAllCars.getModel();
        Car selectedCar=(Car)model.getValueAt(rowindex,0);
        Car c = new Car();
        c.setNameOfCar(txtNameOfCar.getText());
        c.setModelName(txtModelName.getText());
        c.setYearOfManufacture(Integer.parseInt(txtYearOfManufacture.getText()));
        c.setNoOfSeats(Integer.parseInt(txtNoOfSeats.getText()));
//        c.setLocation(txtLocation.getText());
//        c.setMaintenance(txt.getText());
//         c.setAvailability();
 
        allCars.updateCar(rowindex,c);
        populateTable();
       
        
       
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtNameOfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameOfCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameOfCarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNameOfCar;
    private javax.swing.JLabel lblNoOfSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblYearOfManufacture;
    private javax.swing.JTable tblAllCars;
    private javax.swing.JLabel ttlAddCar;
    private javax.swing.JTextField txtModelName;
    private javax.swing.JTextField txtNameOfCar;
    private javax.swing.JTextField txtNoOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYearOfManufacture;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
    
    DefaultTableModel model = (DefaultTableModel) tblAllCars.getModel();
    model.setRowCount(0);

    for (Car car : allCars.getAllCars()){

        Object[] row = new Object[8];
        row[0] = car ;
        row[1] = car.getModelName();
        row[2] = car.getYearOfManufacture();
        row[3] = car.getNoOfSeats();
        row[4] = car.getSerialNumber();
        row[5] = car.getLocation();
        row[6] = car.getMaintenaceCertificate();
        row[7] = car.getAvailability();
        model.addRow(row);

    }


    }
}