/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryManDirectory;

import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CustomerRole.CustomerAreaJPanel;
import userinterface.CustomerRole.CustomerRestaurantOrder;
import userinterface.DeliveryManRole.DeliveryManWorkAreaJPanel;
import userinterface.DeliveryManRole.OrdersDelivery;
import userinterface.RestaurantAdminRole.AdminWorkAreaJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /** 
     * Creates new form MainJFrame
     */
    private EcoSystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount ua;
    RestaurantDirectory rd;

    public MainJFrame() {
        initComponents();
        ecosystem = dB4OUtil.retrieveSystem();
        if(ecosystem == null)
        {
            ecosystem = new EcoSystem(new RestaurantDirectory(),new CustomerDirectory(),new DeliveryManDirectory());
        }
        
        this.setSize(1800, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        mainPageIntro = new javax.swing.JPanel();
        loginSection = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEnterUsernamePassword = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblAssgnSubmitted = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(153, 153, 255));
        navbar.setPreferredSize(new java.awt.Dimension(1800, 100));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_deliver_food_75px.png"))); // NOI18N
        navbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 93, 108));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Food Delivery System");
        jLabel4.setAlignmentY(1.0F);
        navbar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 562, 108));

        btnLogout.setBackground(new java.awt.Color(51, 51, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shutdown_25px_2.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        navbar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 40, -1, 40));

        jPanel2.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 110));

        mainPageIntro.setBackground(new java.awt.Color(255, 153, 204));
        mainPageIntro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(mainPageIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 1270, 990));

        loginSection.setBackground(new java.awt.Color(36, 47, 65));
        loginSection.setPreferredSize(new java.awt.Dimension(135, 998));
        loginSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 51, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_login_25px.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        loginSection.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 40));
        loginSection.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        loginSection.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 170, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");
        loginSection.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        loginSection.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        lblEnterUsernamePassword.setBackground(new java.awt.Color(51, 51, 255));
        lblEnterUsernamePassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Not a regitered user?? Sign Up");
        lblEnterUsernamePassword.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 350, 50));

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Enter Username and Password");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 350, 40));

        lblEnterUsernamePassword.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 40));

        loginSection.add(lblEnterUsernamePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 550, 50));

        lblAssgnSubmitted.setBackground(new java.awt.Color(51, 51, 255));
        lblAssgnSubmitted.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Already a User?? Login !!!");
        lblAssgnSubmitted.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 350, 50));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Enter Username and Password");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 350, 40));

        lblAssgnSubmitted.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 40));

        loginSection.add(lblAssgnSubmitted, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 50));

        jPanel2.add(loginSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 550, 950));

        container.setLayout(new java.awt.CardLayout());
        jPanel2.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 105, 1290, 950));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get user name
        String username = userNameJTextField.getText();
        String password = passwordField.getText();
        UserAccountDirectory userDirectory = ecosystem.getUserAccountDirectory();
        if(userDirectory.authenticateUserLogin(username, password))
        {
        ArrayList<UserAccount> usersList = userDirectory.getUserAccountList();
         mainPageIntro.setVisible(false);
         
        this.ua = userDirectory.authenticateUser(username, password);
        if(ua.getRole().toString().equals("Business.Role.SystemAdminRole"))
        {
            performLogin();
            SystemAdminWorkAreaJPanel sa = new SystemAdminWorkAreaJPanel(container, ecosystem);
            container.add("Sysadmin",sa);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.AdminRole"))
        {
            performLogin();
            AdminWorkAreaJPanel aw = new AdminWorkAreaJPanel(container,ua,ecosystem);
            container.add("RestaurantAdmin",aw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.DeliverManRole"))
        {
           
            performLogin();
            OrdersDelivery dw = new OrdersDelivery(container, ua, ecosystem);
            container.add("DeliveryMan",dw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.CustomerRole"))
        {
            performLogin();
            CustomerRestaurantOrder ca = new CustomerRestaurantOrder(container, ua,ecosystem);
            container.add("Customer",ca);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid credentials");
        }
      
       
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        btnLogout.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        btnLogin.setEnabled(true);
        
        
        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        mainPageIntro.setVisible(true);
//        JPanel blankJP = new JPanel();
//        container.add("blank", blankJP);
//        CardLayout crdLyt = (CardLayout) container.getLayout();
//        crdLyt.next(container);
//        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    public void logOut(EcoSystem ecosystem)
    {
        
    }
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    private void performLogin(){
        btnLogout.setEnabled(true); 
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
        btnLogin.setEnabled(false);
    
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel lblAssgnSubmitted;
    private javax.swing.JPanel lblEnterUsernamePassword;
    public javax.swing.JPanel loginSection;
    private javax.swing.JPanel mainPageIntro;
    private javax.swing.JPanel navbar;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
