/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kishore KVN
 */
public class ManageRestaurantsWorkArena extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantsWorkArena
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CustomerDirectory cd;
    RestaurantDirectory rd;
    public ManageRestaurantsWorkArena(JPanel userProcessContainer , EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        restosTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        restoList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUnamePwd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRestoUpdtPwd = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 204));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Restaurant Directory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 160, -1));

        restosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant username", "password"
            }
        ));
        jScrollPane1.setViewportView(restosTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 103));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        restoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoListActionPerformed(evt);
            }
        });
        add(restoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 124, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Restaurant");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, 91, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        txtUnamePwd.setEditable(false);
        txtUnamePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnamePwdActionPerformed(evt);
            }
        });
        add(txtUnamePwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 124, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 63, -1));
        add(txtRestoUpdtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 124, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Logged in  as   SYSTEM ADMINISTRATOR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 470, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) restosTable.getModel();
        int selectedRow = restosTable.getSelectedRow();
        String userName = (String) df.getValueAt(selectedRow, 0);
        cd = ecosystem.getCustomerDirectory();
        df.removeRow(selectedRow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUnamePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnamePwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnamePwdActionPerformed

    private void restoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoListActionPerformed
        // TODO add your handling code here:
        String resto = (String) restoList.getSelectedItem();
        rd = ecosystem.getRestaurantDirectory();
        ArrayList<Restaurant> restos = rd.getRestaurantList();
        for(Restaurant r: restos)
        {
            if(r.getName().equals(resto))
            {
                txtUnamePwd.setText(r.getUserAccount().getUsername());
                txtRestoUpdtPwd.setText(r.getUserAccount().getPassword());}
        }
    }//GEN-LAST:event_restoListActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String resto = (String) restoList.getSelectedItem();
        String pwd = txtRestoUpdtPwd.getText();
        rd = ecosystem.getRestaurantDirectory();
        ArrayList<Restaurant> restos = rd.getRestaurantList();
        for(Restaurant r: restos)
        {
            if(r.getName().equals(resto))
            {
                r.getUserAccount().setPassword(pwd);
                JOptionPane.showMessageDialog(this, "Password Updated");
            }
        }
        populateTable();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> restoList;
    private javax.swing.JTable restosTable;
    private javax.swing.JTextField txtRestoUpdtPwd;
    private javax.swing.JTextField txtUnamePwd;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        rd = ecosystem.getRestaurantDirectory();
        DefaultTableModel df = (DefaultTableModel) restosTable.getModel();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        df.setRowCount(0);
        ArrayList<Restaurant> restos = rd.getRestaurantList();
        for(Restaurant r: restos)
        {
            String[] row = {r.getUserAccount().getUsername(),r.getUserAccount().getPassword()};
            df.addRow(row);
            dc.addElement(r.getName());
        }
        restosTable.setModel(df);
        restoList.setModel(dc);
    }
}
