/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Doctor;

import model.Encounter;
import model.HealthcareSystem;
import model.Patient;
import model.PatientDirectory;
import model.VitalSign;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author KishoreKVN
 */
public class AddNewEncounter extends javax.swing.JPanel {
    
    JPanel workArea; 
    HealthcareSystem healthcareSystem;
    /**
     * Creates new form RecordNewEncounter
     */
    public AddNewEncounter(JPanel workArea, HealthcareSystem healthcareSystem) {
        initComponents();
        
        this.workArea = workArea;
        this.healthcareSystem = healthcareSystem;
        populatePatientCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        patientComboBox = new javax.swing.JComboBox<>();
        lblSampleAge = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBp = new javax.swing.JTextField();
        txtTemperature = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRr = new javax.swing.JTextField();
        btnAddCSV2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 51, 255));

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 255, 255));
        lblDate.setText("Encouter Date");

        lblPatientName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(204, 255, 255));
        lblPatientName.setText("Patient Name");

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyReleased(evt);
            }
        });

        patientComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSampleAge.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addComponent(lblSampleAge, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSampleAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 590, 100));

        btnSave.setBackground(new java.awt.Color(0, 153, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_save_as_25px.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Enter new encounter details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(lblTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 60));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(179, 22));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vital Signs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 48));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Blood Pressure");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, -1, -1));

        txtBp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(txtBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 74, 134, -1));

        txtTemperature.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 134, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Heart Rate");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 128, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Temperature");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        txtHr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(txtHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 127, 134, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Respiratory Rate");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        txtRr.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(txtRr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 134, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 590, 200));

        btnAddCSV2.setBackground(new java.awt.Color(255, 204, 204));
        btnAddCSV2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddCSV2.setForeground(new java.awt.Color(51, 51, 255));
        btnAddCSV2.setText("Add CSV");
        btnAddCSV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCSV2ActionPerformed(evt);
            }
        });
        add(btnAddCSV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        
        Patient selectedPatient = (Patient) patientComboBox.getSelectedItem();
        List<Encounter> encounterHistory = selectedPatient.getEncounterHistory().getEncounterHistory();
        Encounter newEncounter = new Encounter(); 
//        String[] complaints = new String[3];
//
//        if(selectedPatient != null){
//         
//            
//            if(!txtComplaint_1.getText().isEmpty())
//                complaints[0] = txtComplaint_1.getText();
//           
//            
//           if(!txtComplaint_2.getText().isEmpty())
//                complaints[1] = txtComplaint_2.getText();
//           
//           
//           if(!txtComplaint_3.getText().isEmpty()){
//                complaints[2] = txtComplaint_3.getText();
//           
//           }
//            newEncounter.setCompaints(complaints);
//            
//            if(txtDiagnosis.getText().isEmpty()){
//                
//                JOptionPane.showMessageDialog(this, "Fill in Diagnosis field", "Warning", JOptionPane.WARNING_MESSAGE);
//                return;
//            } 
//            
        if(selectedPatient != null){
            
            newEncounter.setPatient(selectedPatient);
            newEncounter.setEncounterDate(jDateChooser1.getDate());
            
          try{
         newEncounter.setVitalSign(new VitalSign(Integer.parseInt(txtRr.getText()),Integer.parseInt(txtBp.getText()),
            Integer.parseInt(txtHr.getText()), Double.parseDouble(txtTemperature.getText())));
        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(this, "Fill in All the fields along with valid data format", "Warning", JOptionPane.WARNING_MESSAGE);
             return;
        }

         newEncounter.setHealthStatus();
         encounterHistory.add(newEncounter);            
         selectedPatient.updateHealthStatus();

         JOptionPane.showMessageDialog(this, "Encounter details added to patient profile", "Information", JOptionPane.INFORMATION_MESSAGE);
         backAction();

        }
 
        else{
            JOptionPane.showMessageDialog(this, "Select a patient to add encounter details", "Warning", JOptionPane.WARNING_MESSAGE);
           
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jDateChooser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyReleased
        // TODO add your handling code here:
//         Patient selectedPatient = (Patient) patientComboBox.getSelectedItem();
//        List<Encounter> encounterHistory = selectedPatient.getEncounterHistory().getEncounterHistory();
//        Encounter newEncounter = new Encounter(); 
//        lblSampleAge.setText(Integer.toString(newEncounter.getAge()));
    }//GEN-LAST:event_jDateChooser1KeyReleased

    private void btnAddCSV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCSV2ActionPerformed
        // TODO add your handling code here:
//        
//        String path = "C:\\Users\\LENOVO\\Desktop\\patients.csv";
//        String line = "";
//
//       try{
//        BufferedReader br;
//        br = new BufferedReader(new FileReader(path));
//        
//        int i = 0;
//        int patientId=0;
//        String name = ""; long phone= 0;
//        String email=""; int age = 0;
//        String houseNumber = "";
//        String streetName = "";
//        String communityName = "";
//        int zipCode = 0;
//          
//        while((line=br.readLine()) != null){
//            String[] values = line.split(",");
//            Encounter e = new Encounter();
//               
//            e.setPatientId(Integer.parseInt(values[0]));
//            e.setName(values[1]);
//            e.setAge(Integer.parseInt(values[2]));
//            e.setPhone(Long.parseLong(values[3]));
//            e.setEmail(values[4]);
//            //p.setHouseNumber(Integer.parseInt(values[5]));
//
//            encounterHistory.addPatient(p);
//            i++;
//                 
//                
//            }
//            
//        JOptionPane.showMessageDialog(this, String.valueOf(i) + " Encounters have been added to Encounter History");
//        //refreshTable();
//          
//       } 
//   
//        catch ( FileNotFoundException e){
//            JOptionPane.showMessageDialog(this, "The error message has been caught");
//         } 
//         catch (IOException ex)
//         {
//             
//         }

        
        
    }//GEN-LAST:event_btnAddCSV2ActionPerformed
    
    private void backAction() {
        workArea.remove(this);
//        DoctorWorkAreaJPanel doctorWorkAreaJPanel = new DoctorWorkAreaJPanel(workArea, healthcareSystem);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCSV2;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblSampleAge;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JComboBox<Object> patientComboBox;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtHr;
    private javax.swing.JTextField txtRr;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables

    private void populatePatientCombo() {
        patientComboBox.removeAllItems();
        
        for(Patient p : healthcareSystem.getPatientDirectory().getPatientDirectory()){
            patientComboBox.addItem(p);
        }
    }
}
