/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package ui.Doctor;

import model.HealthcareSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import ui.LoginPanel;

/**
 *
 * @author  KishoreKVN
 */
public class DoctorJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    HealthcareSystem healthcareSystem;
    
    /** Creates new form AdminWorkAreaJPanel */
    public DoctorJPanel(JPanel mainWorkArea, HealthcareSystem healthcareSystem) {
        
        this.mainWorkArea = mainWorkArea;
        this.healthcareSystem = healthcareSystem;
        
        initComponents();
        lblWelcome.setText("Hello Doctor!!!  Welcome Back...");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnRecordEncounter = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnReports = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        splitPane.setDividerLocation(50);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(51, 102, 255));

        btnRecordEncounter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRecordEncounter.setForeground(new java.awt.Color(51, 51, 255));
        btnRecordEncounter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_add_50px.png"))); // NOI18N
        btnRecordEncounter.setText("New encounter");
        btnRecordEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordEncounterActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 153, 153));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shutdown_25px.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 102));
        lblWelcome.setText("<WelcomeMsg>");

        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(51, 51, 255));
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_combo_chart_50px.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnRecordEncounter)
                .addGap(66, 66, 66)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(57, 57, 57))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRecordEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWelcome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut)))
                .addContainerGap())
        );

        splitPane.setTopComponent(menuBar);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordEncounterActionPerformed
        
        RecordNewEncounter recordNewEncounter = new RecordNewEncounter(workArea, healthcareSystem);
        workArea.add("RecordNewEncounter", recordNewEncounter);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
     
    }//GEN-LAST:event_btnRecordEncounterActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        
        mainWorkArea.remove(this);
        
        Component[] components = mainWorkArea.getComponents();
        Component component = components[components.length - 1];
        
        LoginPanel loginScreenPanel = (LoginPanel) component;
        loginScreenPanel.populatePatientsCombo();
        
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
                
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        
        DoctorViewReport doctorViewReport = new DoctorViewReport(workArea, healthcareSystem.getPatientDirectory());
        workArea.add("DoctorViewReport", doctorViewReport);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnReportsActionPerformed

    @Override
    public String toString(){
        return "Doctor";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRecordEncounter;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
    
}
