/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.FinalOrder;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kishore KVN
 */
public class OrdersDelivery extends javax.swing.JPanel {

    /**
     * Creates new form OrdersDelivery
     */
    JPanel userProcessContainer;

     UserAccount userAccount;
    EcoSystem ecosystem;
    RestaurantDirectory rd;
    CustomerDirectory cd;
    DeliveryManDirectory dd;
    Restaurant resto;
    public OrdersDelivery(JPanel userProcessContainer, UserAccount account,EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        initComponents();

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryTable = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliveryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant", "Customer", "Item", "Order time", "status", "OrderId"
            }
        ));
        jScrollPane1.setViewportView(deliveryTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 870, 290));

        btnAssignToMe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(51, 51, 255));
        btnAssignToMe.setText("Assign to me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, -1));

        btnProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(51, 51, 255));
        btnProfile.setText("View Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Orders to be delivered");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1300, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) deliveryTable.getModel();
        int selectedRow = deliveryTable.getSelectedRow();
        String orderId = df.getValueAt(selectedRow,5).toString();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        f.setStatus("DeliveryMan Assigned");
        f.setDeliveryMan(userAccount.getUsername());
        dd = ecosystem.getDeliveryManDirectory();
        DeliveryMan d = dd.getDeliveryMan(userAccount);
        d.addDeliveredOrder(f);
        populateTable();
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        DeliveryProfile dp = new DeliveryProfile(userProcessContainer, userAccount, ecosystem);
            userProcessContainer.add("DeliveryProfile",dp);
            CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnProfile;
    private javax.swing.JTable deliveryTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dm = (DefaultTableModel) deliveryTable.getModel();
        dm.setRowCount(0);
        rd = ecosystem.getRestaurantDirectory();
        ArrayList<FinalOrder> orders;
        ArrayList<Restaurant> restos = rd.getRestaurantList();
        for(Restaurant r: restos)
        {
            if(r.getAcceptedOrders() == null)
                r.setAcceptedOrders(new ArrayList<FinalOrder>());
            orders = r.getAcceptedOrders();
            for(FinalOrder f: orders)
            {
                String[] row = {r.getName(),f.getCustomer(),f.getItem(),f.getDate(),f.getStatus(),f.getOrderId()};
                dm.addRow(row);
            }
        }
        deliveryTable.setModel(dm);
            
    }
}
