/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.FinalOrder;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kishore KVN
 */
public class manageOrders extends javax.swing.JPanel {

    /**
     * Creates new form manageOrders
     */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount ua;
    Restaurant resto;
    RestaurantDirectory rd;
    CustomerDirectory cd;
    ArrayList<FinalOrder> ordersList;
    DeliveryManDirectory dd;
    public manageOrders(JPanel userProcessContainer,Restaurant resto,EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.resto = resto;
        this.ecosystem = ecosystem;
        initComponents();
        populatetree();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersAvailble = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statusOrders = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        delDropDown = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delCusto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        delItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        delList = new javax.swing.JComboBox<>();
        btnAssignDel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("All available Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        ordersAvailble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Item", "Date"
            }
        ));
        jScrollPane1.setViewportView(ordersAvailble);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 437, 169));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel2.setText("Current and previous orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 166, -1));

        statusOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Item", "status", "Delivery", "Comment", "OrderId", "Order date"
            }
        ));
        jScrollPane3.setViewportView(statusOrders);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 540, 167));

        jLabel3.setText("Assign DeliveryMan");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 92, -1));

        delDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDropDownActionPerformed(evt);
            }
        });
        add(delDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 100, -1));

        jLabel4.setText("OrderId");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 62, -1));

        jLabel5.setText("Customer:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 62, -1));

        delCusto.setEditable(false);
        delCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCustoActionPerformed(evt);
            }
        });
        add(delCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 100, -1));

        jLabel6.setText("Item");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 360, -1, -1));

        delItem.setEditable(false);
        add(delItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 360, 84, -1));

        jLabel7.setText("DeliveryMan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, -1, -1));

        add(delList, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 100, -1));

        btnAssignDel.setText("assign");
        btnAssignDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDelActionPerformed(evt);
            }
        });
        add(btnAssignDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        
        if(resto.getAcceptedOrders() == null)
            resto.setAcceptedOrders(new ArrayList<FinalOrder>());
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        rd = ecosystem.getRestaurantDirectory();
        int orderId = rd.generateOrderId();
        FinalOrder fo = new FinalOrder();
        DefaultTableModel df = (DefaultTableModel) ordersAvailble.getModel();
        
          int selectedRow = ordersAvailble.getSelectedRow();
          String customer = df.getValueAt(selectedRow,0).toString();
          String item = df.getValueAt(selectedRow, 1).toString();
          String date = df.getValueAt(selectedRow,2).toString();
          fo.setOrderId(String.valueOf(orderId));
          fo.setCustomer(customer);
          fo.setItem(item);
          fo.setDate(date);
          fo.setRestaurant(resto.getName());
          fo.setStatus("Order Accepted");
          orders.add(fo);
          df.removeRow(selectedRow);
          populatetree();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void delCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delCustoActionPerformed

    private void delDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDropDownActionPerformed
        // TODO add your handling code here:
        String orderId =(String) delDropDown.getSelectedItem();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        delCusto.setText(f.getCustomer());
        delItem.setText(f.getItem());
        dd = ecosystem.getDeliveryManDirectory();
        ArrayList<DeliveryMan> deliveryMen = dd.getDeliveryDirectory();
        for(DeliveryMan d: deliveryMen)
        {
            df.addElement(d.getName());
        }
        delList.setModel(df);
    }//GEN-LAST:event_delDropDownActionPerformed

    private void btnAssignDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDelActionPerformed
        // TODO add your handling code here:
        String orderId =(String) delDropDown.getSelectedItem();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        f.setDeliveryMan((String) delList.getSelectedItem());
        f.setStatus("DeliveryMan Assigned");
        populatetree();
        delCusto.setText("");
        delItem.setText("");
    }//GEN-LAST:event_btnAssignDelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"RestaurantAdmin");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAssignDel;
    private javax.swing.JTextField delCusto;
    private javax.swing.JComboBox<String> delDropDown;
    private javax.swing.JTextField delItem;
    private javax.swing.JComboBox<String> delList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable ordersAvailble;
    private javax.swing.JTable statusOrders;
    // End of variables declaration//GEN-END:variables

    private void populatetree() {
        String resoName = resto.getName();
        cd = ecosystem.getCustomerDirectory();
        DefaultTableModel dt = (DefaultTableModel) ordersAvailble.getModel();
        dt.setRowCount(0);
        ArrayList<Customer> customers = cd.getCustomerList();
        for(Customer c: customers)
        {
            ArrayList<Order> orders = c.getPreviousOrders();
            for(Order o: orders)
            {
                if(o.getRestaurant().equals(resoName))
                {
                    String[] row = {c.getCustomerName(),o.getItem(),o.getEntryDateTime().toString()};
                    dt.addRow(row);
                }
            }
        }
        
        ordersAvailble.setModel(dt);
        
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        DefaultTableModel df = (DefaultTableModel) statusOrders.getModel();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        df.setRowCount(0);
        for(FinalOrder f: orders)
        {
            String[] row = {f.getCustomer(),f.getItem(),f.getStatus(),f.getDeliveryMan(),f.getReview(),f.getOrderId(),f.getDate()};
            df.addRow(row);
            if(f.getDeliveryMan() == null)
            dc.addElement(f.getOrderId());
        }
        
        statusOrders.setModel(df);
        delDropDown.setModel(dc);
        
    }
}
